/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getLet <em>Let</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getIn <em>In</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet()
 * @model
 * @generated
 */
public interface Let extends Primary
{
  /**
   * Returns the value of the '<em><b>Let</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Let</em>' containment reference.
   * @see #setLet(dk.sdu.mmmi.mdsd.math.Math)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_Let()
   * @model containment="true"
   * @generated
   */
  dk.sdu.mmmi.mdsd.math.Math getLet();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getLet <em>Let</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Let</em>' containment reference.
   * @see #getLet()
   * @generated
   */
  void setLet(dk.sdu.mmmi.mdsd.math.Math value);

  /**
   * Returns the value of the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' containment reference.
   * @see #setIn(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_In()
   * @model containment="true"
   * @generated
   */
  Exp getIn();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getIn <em>In</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' containment reference.
   * @see #getIn()
   * @generated
   */
  void setIn(Exp value);

} // Let
